version: "3"

services:
    frontend:
        container_name: swap_nuxt_container
        build:
            context: .
            dockerfile: ./docker/nuxt/Dockerfile
        volumes:
            - ./frontend:/app/frontend
        ports:
            - 3000:3000
        tty: true

    backend:
        container_name: swap_nodejs_container
        build:
            context: .
            dockerfile: ./docker/nodejs/Dockerfile
        volumes:
            - ./backend:/app/backend
        ports:
            - 8000:8000
        tty: true

    nginx:
        image: nginx
        container_name: swap_nginx_container
        ports:
            - 80:80
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    mysql:
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        container_name: swap_mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nuxt-nodejs-app
            TZ: "Asia/Tokyo"
        volumes:
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - ./docker/mysql/mysql_data:/var/lib/mysql
        ports:
            - 3306:3306
        links:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: swap_phpmyadmin_container
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - mysql
        ports:
            - 1234:80
        volumes:
            - /sessions
